import Head from "next/head";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Pixelformers - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Here is some text</main>
    </div>
  );
};

export default Home;
