import Head from "next/head";
import Layout from "../components/Layout/Layout";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Pixelformers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout />
    </div>
  );
};

export default Home;
