import Head from "next/head";
import safeJsonStringify from "safe-json-stringify";
import Image from "next/image";
import { documentToReactComponents } from "@contentful/rich-text-react-renderer";
import { BLOCKS } from "@contentful/rich-text-types";

import { createClientFunc } from "./api/contentful";

const Series = ({ series: { items } }) => {
  return (
    <div>
      <Head>
        <title>Pixelformers - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <div>
          {items.map((s) => {
            const { seriesName, seriesReference } = s.fields;
            return (
              <>
                <h2>{seriesName}</h2>
                {seriesReference.map((sprites) => {
                  const {
                    spriteName,
                    primaryFunction,
                    image: {
                      fields: { details, url },
                    },
                    faction,
                    bio,
                    altMode,
                  } = sprites.fields;

                  return (
                    <div>
                      <p>{spriteName}</p>
                      <p>{primaryFunction}</p>
                      <p>{altMode}</p>
                      <p>{faction}</p>
                      {documentToReactComponents(bio)}
                    </div>
                  );
                })}
              </>
            );
          })}
        </div>
      </section>
    </div>
  );
};

export default Series;

export const getStaticProps = async () => {
  const contentfulClient = createClientFunc();

  const seriesRes = await contentfulClient.getEntries({
    content_type: "series",
  });

  return {
    props: {
      series: JSON.parse(safeJsonStringify(seriesRes)),
    },
  };
};
