import Head from "next/head";
import safeJsonStringify from "safe-json-stringify";

import { createClientFunc } from "./api/contentful";

const Sprite = ({ sprite }) => {
  console.log(sprite);
  return (
    <div>
      <Head>
        <title>Pixelformers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Sprite;

export const getStaticProps = async () => {
  const contentfulClient = createClientFunc();

  const spriteRes = await contentfulClient.getEntries({
    content_type: "sprite",
  });
  const sprite = JSON.parse(safeJsonStringify(spriteRes));

  return {
    props: {
      sprite,
    },
  };
};
